### ISSUE TITLE
Could not find a version that satisfies the requirement torch==1.6.0+cu101

### ISSUE THREAD

**Issue by WASasquatch** [ai-forever/ghost#63]
I have PyTorch CUDA 11.6 already installed, and cannot install older versions because of other projects. What do we do? 

```txt
ERROR: Could not find a version that satisfies the requirement torch==1.6.0+cu101 (from versions: 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.1, 1.10.1+cpu, 1.10.1+cu102, 1.10.1+cu111, 1.10.1+cu113, 1.10.2, 1.10.2+cpu, 1.10.2+cu102, 1.10.2+cu111, 1.10.2+cu113, 1.11.0, 1.11.0+cpu, 1.11.0+cu113, 1.11.0+cu115, 1.12.0, 1.12.0+cpu, 1.12.0+cu113, 1.12.0+cu116, 1.12.1, 1.12.1+cpu, 1.12.1+cu113, 1.12.1+cu116, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117)
ERROR: No matching distribution found for torch==1.6.0+cu101
```

**Comment by RijulGupta-DM** [comment]
You should create a separate conda environment from scratch. Keep separate environments for separate projects, unless it's absolutely critical to use the same environment, maybe because they are used in conjunction. 

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

You could also just use the most recent version of torch, I don't think it'll matter that much (don't quote me on that).

**Comment by Dutch77** [comment]
use docker image
https://github.com/ai-forever/ghost/issues/51

**Comment by WASasquatch** [comment]
> use docker image #51

I'll try a conda. I was trying to avoid that because I have like dozens of environments, most with the same redundant stuff, just to run one thing. It's getting out of hand with Python stuff lol It's a space killer

**Comment by Dutch77** [comment]
> > use docker image #51
> 
> I'll try a conda. I was trying to avoid that because I have like dozens of environments, most with the same redundant stuff, just to run one thing. It's getting out of hand with Python stuff lol It's a space killer

Problem with your approach is installed packages is not everything in this case. You need proper nvidia drivers with proper OS, because some of those packages are not released in version you need for your system. So u have to find some combination of different version of packages and try if those work with this project.

My solution with docker works because it's using exact system as author of this project -> cuda 10.1, cudnn7 and ubuntu18.04.

Maybe it's a space killer, but it's painless :D
